function tq(src,pre){const q={filters:Object.assign({},pre||{}),eq(k,v){this.filters[k]=v;return this},in(c,vals){this.filters[c]=vals;return this},order(o){this.orderBy=o;return this},maybeSingle(){const o=src.slice().filter(x=>Object.keys(this.filters).every(k=>x[k]===this.filters[k]));return Promise.resolve(o.length?{data:o[0],error:null}:{data:null,error:null})}};q.then=function(r){let out=src.slice().filter(x=>Object.keys(this.filters).every(k=>{const f=this.filters[k];return Array.isArray(f)?f.includes(x[k]):x[k]===f}));if(this.orderBy){const c=this.orderBy.column,a=this.orderBy.ascending;out=out.slice().sort((x,y)=>a?(x[c]>y[c]?1:-1):(x[c]<y[c]?1:-1));}r({data:out,error:null});return Promise.resolve({data:out,error:null})};return q}
function ins(t,row,src){uidSeq++;const rec=Object.assign({id:t+'-uuid-'+uidSeq},row);src.push(rec);return{data:rec,error:null}}
// 删除行（pets/equip_items 共用）：in = 批量（数组），eq = 单条；delCalls 记录删除数量
function delRows(src,c,v,isIn,res){const vals=isIn?v:[v];delCalls.push(vals.length);if(globalThis.failDelete){res({data:null,error:{message:'d'}});return;}for(const x of vals){const i=src.findIndex(r=>r[c]===x);if(i>=0)src.splice(i,1);}res({data:null,error:null})}
supabase.createClient=function(){return{auth:{getSession:async()=>({data:{session:session}}),getUser:async()=>(session?{data:{user:session.user},error:null}:{data:{user:null},error:null}),signInWithPassword:async({email})=>{session={user:{id:'user-a',email}};return{data:{session},error:null}},signUp:async()=>({data:{session:null,user:null},error:null}),signOut:async()=>{session=null;return{error:null}}},
from(t){
if(t==='materials')return{select:()=>tq(materialsTable,session?{user_id:session.user.id}:{})};
if(t==='pets'||t==='equip_items'){const src=t==='pets'?petsTable:itemsTable;const flt=session?{user_id:session.user.id}:{};return{
select:()=>tq(src,flt),insert:row=>({select:()=>({single:async()=>ins(t,row,src)})}),
update:(patch)=>({eq:(c,v)=>({then:(res)=>{if(globalThis.failUpdate){res({data:null,error:{message:'u'}});return;}const r=src.find(x=>x[c]===v);if(r)Object.assign(r,patch);res({data:null,error:null})}})}),
delete:()=>({in:(c,vals)=>({then:(res)=>delRows(src,c,vals,true,res)}),eq:(c,v)=>({then:(res)=>delRows(src,c,v,false,res)})})}};
if(t==='pet_listings'||t==='equip_listings'){const src=t==='pet_listings'?listingsTable:itemListTable;return{select:()=>tq(src,{}),insert:row=>({select:()=>({single:async()=>{const r=ins(t,row,src);r.data.status='active';return r}})})}};
if(t==='trade_records')return{select:()=>tq(typeof tradeTable!=='undefined'?tradeTable:[],{})};
if(t==='pet_egg')return{select:()=>tq(petEggTable,{}),insert:row=>({select:()=>({single:async()=>ins(t,row,petEggTable)})}),update:(patch)=>({eq:(c,v)=>({then:(res)=>{const r=petEggTable.find(x=>x[c]===v);if(r)Object.assign(r,patch);res({data:null,error:null})}})}),delete:()=>({eq:(c,v)=>({then:(res)=>{const i=petEggTable.findIndex(x=>x[c]===v);if(i>=0)petEggTable.splice(i,1);res({data:null,error:null})}})})};
return{select:()=>tq([],{})};},
rpc:async(fn,args)=>{rpcCalls.push(fn);if(fn==='add_material'){const uid=session?session.user.id:'anon';const r=materialsTable.find(x=>x.user_id===uid&&x.name===args.p_name);if(r)r.quantity+=args.p_amount;else materialsTable.push({id:'m'+(++uidSeq),user_id:uid,name:args.p_name,quantity:args.p_amount});return{data:null,error:null}}if(fn==='spend_material'){const uid=session?session.user.id:'anon';const r=materialsTable.find(x=>x.user_id===uid&&x.name===args.p_name&&x.quantity>=args.p_amount);if(!r)return{data:false,error:null};r.quantity-=args.p_amount;return{data:true,error:null}}if(fn==='buy_pet'||fn==='buy_equip'){const table=fn==='buy_pet'?listingsTable:itemListTable;const ik=fn==='buy_pet'?'pet_id':'item_id';const ot=fn==='buy_pet'?petsTable:itemsTable;const l=table.find(x=>x.id===args.p_listing_id&&x.status==='active');if(!l)return{data:'notfound',error:null};const it=ot.find(x=>x.id===l[ik]);if(!it)return{data:'notfound',error:null};it.user_id=session.user.id;l.status='sold';return{data:'ok',error:null}}if(fn==='bot_buy_equip'){const l=itemListTable.find(x=>x.id===args.p_listing_id&&x.status==='active');if(!l)return{data:'notfound',error:null};const tax=Math.floor(l.material_qty/8)*1;const net=l.material_qty-tax;const srow=materialsTable.find(x=>x.user_id===l.seller_id&&x.name===l.material_type);if(srow)srow.quantity+=net;else materialsTable.push({id:'mat-'+(++uidSeq),user_id:l.seller_id,name:l.material_type,quantity:net});tradeTable.push({id:'tr-'+(++uidSeq),player_id:'流浪商人',role:'buy',item_name:l.item_name,material_type:l.material_type,price_qty:l.material_qty,tax_qty:0,net_qty:l.material_qty,created_at:new Date().toISOString()});tradeTable.push({id:'tr-'+(++uidSeq),player_id:l.seller_id,role:'sell',item_name:l.item_name,material_type:l.material_type,price_qty:l.material_qty,tax_qty:tax,net_qty:net,created_at:new Date().toISOString()});const ii=itemsTable.findIndex(x=>x.id===l.item_id);if(ii>=0)itemsTable.splice(ii,1);const li=itemListTable.findIndex(x=>x.id===l.id);if(li>=0)itemListTable.splice(li,1);return{data:'ok',error:null}}return{data:null,error:{message:'x'}}}}}
